ALTER TABLE "DailyReport" ADD COLUMN "metadata" JSONB NOT NULL DEFAULT '{}';
ALTER TABLE "Certificate" ADD COLUMN "metadata" JSONB NOT NULL DEFAULT '{}';
ALTER TABLE "Dossier" ADD COLUMN "metadata" JSONB NOT NULL DEFAULT '{}';
ALTER TABLE "Payroll" ADD COLUMN "metadata" JSONB NOT NULL DEFAULT '{}';
ALTER TABLE "PerDiem" ADD COLUMN "metadata" JSONB NOT NULL DEFAULT '{}';
ALTER TABLE "Lodging" ADD COLUMN "metadata" JSONB NOT NULL DEFAULT '{}';
ALTER TABLE "ConcreteOrder" ADD COLUMN "metadata" JSONB NOT NULL DEFAULT '{}';