import type { Work } from "./types";

export const works: Work[] = [
  {
    id: "work-001",
    code: "OB-2026-001",
    name: "SENASA El Sombrero · Oficina y Laboratorio",
    client: "SENASA",
    city: "El Sombrero",
    contractAmount: 178_000_000,
    targetBudget: 143_200_000,
    actualCost: 144_358_000,
    physicalProgress: 61,
    financialProgress: 58,
    collectedAmount: 92_000_000,
    margin: 18.9,
    responsible: "Ing. Martín Gómez",
    status: "Normal",
    image: "/assets/laboratory.webp",
  },
  {
    id: "work-002",
    code: "OB-2026-002",
    name: "Hospital San Juan Bautista · Adecuación eléctrica",
    client: "Ministerio de Salud Pública",
    city: "Santo Tomé",
    contractAmount: 242_000_000,
    targetBudget: 204_000_000,
    actualCost: 210_056_000,
    physicalProgress: 74,
    financialProgress: 72,
    collectedAmount: 151_000_000,
    margin: 13.2,
    responsible: "Ing. Víctor Encina",
    status: "Normal",
    image: "/assets/electrical.webp",
  },
  {
    id: "work-003",
    code: "OB-2026-003",
    name: "Cordón cuneta y desagües urbanos",
    client: "Municipalidad de Perugorría",
    city: "Perugorría",
    contractAmount: 98_000_000,
    targetBudget: 88_500_000,
    actualCost: 90_062_000,
    physicalProgress: 47,
    financialProgress: 53,
    collectedAmount: 31_000_000,
    margin: 8.1,
    responsible: "Téc. Carlos Ruiz",
    status: "Atención",
    image: "/assets/roadworks.webp",
  },
  {
    id: "work-004",
    code: "OB-2026-004",
    name: "Escuela rural · Cerramiento perimetral",
    client: "Ministerio de Educación",
    city: "Ituzaingó",
    contractAmount: 126_000_000,
    targetBudget: 103_000_000,
    actualCost: 104_958_000,
    physicalProgress: 82,
    financialProgress: 78,
    collectedAmount: 84_000_000,
    margin: 16.7,
    responsible: "Arq. Laura Benítez",
    status: "Normal",
    image: "/assets/laboratory.webp",
  },
  {
    id: "work-005",
    code: "OB-2026-005",
    name: "Loteo El Perichón · Infraestructura MT/BT",
    client: "Desarrollos El Perichón SA",
    city: "Corrientes",
    contractAmount: 310_000_000,
    targetBudget: 251_000_000,
    actualCost: 246_760_000,
    physicalProgress: 35,
    financialProgress: 31,
    collectedAmount: 76_000_000,
    margin: 20.4,
    responsible: "Ing. José Biloni",
    status: "Normal",
    image: "/assets/electrical.webp",
  },
  {
    id: "work-006",
    code: "OB-2026-006",
    name: "Ampliación Centro de Salud",
    client: "Ministerio de Salud Pública",
    city: "Bella Vista",
    contractAmount: 112_000_000,
    targetBudget: 93_000_000,
    actualCost: 94_640_000,
    physicalProgress: 68,
    financialProgress: 64,
    collectedAmount: 53_000_000,
    margin: 15.5,
    responsible: "Arq. Laura Benítez",
    status: "Normal",
    image: "/assets/laboratory.webp",
  },
  {
    id: "work-007",
    code: "OB-2026-007",
    name: "Pavimento urbano · Etapa II",
    client: "Municipalidad de Goya",
    city: "Goya",
    contractAmount: 94_000_000,
    targetBudget: 79_000_000,
    actualCost: 80_652_000,
    physicalProgress: 56,
    financialProgress: 52,
    collectedAmount: 39_000_000,
    margin: 14.2,
    responsible: "Téc. Diego Silva",
    status: "Normal",
    image: "/assets/roadworks.webp",
  },
  {
    id: "work-008",
    code: "OB-2026-008",
    name: "Parque Industrial · Red MT/BT",
    client: "Parque Industrial Corrientes SA",
    city: "Corrientes",
    contractAmount: 80_000_000,
    targetBudget: 65_000_000,
    actualCost: 66_320_000,
    physicalProgress: 43,
    financialProgress: 40,
    collectedAmount: 24_000_000,
    margin: 17.1,
    responsible: "Ing. Víctor Encina",
    status: "Normal",
    image: "/assets/electrical.webp",
  },
];

export const alerts = [
  {
    level: "high",
    title: "Certificado Nº 4 pendiente de cobro",
    detail: "OB-2026-001 · 17 días en trámite",
  },
  {
    level: "medium",
    title: "Expediente sin movimiento",
    detail: "OB-2026-003 · 21 días sin novedades",
  },
  {
    level: "medium",
    title: "Service de camión grúa próximo",
    detail: "Flota · vence en 8 días",
  },
  {
    level: "low",
    title: "Cemento por debajo del stock mínimo",
    detail: "Depósito central · faltan 74 bolsas",
  },
];

export const cashflow = [
  { month: "Abr", income: 72, expense: 48 },
  { month: "May", income: 54, expense: 61 },
  { month: "Jun", income: 88, expense: 64 },
  { month: "Jul", income: 96, expense: 72 },
  { month: "Ago", income: 83, expense: 67 },
  { month: "Sep", income: 112, expense: 78 },
];

export const activity = [
  { user: "Ana Gómez", action: "registró OC-2026-0048", module: "Compras", time: "hace 12 min" },
  { user: "Víctor Encina", action: "subió memoria MT v2", module: "Ingeniería", time: "hace 38 min" },
  { user: "María López", action: "actualizó expediente", module: "Expedientes", time: "hace 1 h" },
  { user: "Carlos Ruiz", action: "cerró parte diario", module: "Avances", time: "hace 2 h" },
];
