import type { ModuleDefinition } from "./types";

export const modules: ModuleDefinition[] = [
  { slug: "dashboard", label: "Dashboard general", group: "Principal", icon: "LayoutDashboard", summary: "Indicadores consolidados de obras, finanzas, plazos e impuestos.", features: ["Obras activas", "Facturación", "Cobros", "Caja y bancos", "Rentabilidad", "Alertas"] },
  { slug: "works", label: "Obras", group: "Principal", icon: "HardHat", summary: "Alta, seguimiento y tablero individual de cada obra y centro de costo.", features: ["Cliente y contrato", "Ubicación", "Plazo", "Monto", "Responsables", "Dashboard por obra"] },
  { slug: "technical-workspace", label: "Mi trabajo técnico", group: "Principal", icon: "ClipboardCheck", summary: "Bandeja personal del técnico con tareas, vencimientos, obras, documentos y entregables.", features: ["Tareas asignadas", "Prioridades", "Vencimientos", "Obras", "Entregables", "Revisión técnica"] },
  { slug: "notifications", label: "Notificaciones", group: "Principal", icon: "Bell", summary: "Centro de avisos del usuario con canales in-app, email y push preparados.", features: ["Avisos", "Vencimientos", "Asignaciones", "Aprobaciones", "Alertas", "Preferencias"] },
  { slug: "architecture", label: "Arquitectura", group: "Técnica", icon: "Building2", summary: "Proyectos arquitectónicos, planos, cómputos y revisiones.", features: ["Proyectos", "Planos", "Cómputos", "Revisiones", "Versiones", "Aprobaciones"] },
  { slug: "engineering", label: "Ingeniería", group: "Técnica", icon: "DraftingCompass", summary: "Memorias, cálculos y planos de ingeniería con trazabilidad.", features: ["Proyectos", "Memorias", "Cálculos", "Planos", "Revisiones", "Aprobaciones"] },
  { slug: "documents", label: "Documentación", group: "Técnica", icon: "FolderArchive", summary: "Repositorio documental versionado con hash e historial.", features: ["PDF / Office", "DWG / DXF", "Imágenes", "ZIP", "Hash SHA-256", "Baja lógica"] },
  { slug: "budgets", label: "Presupuestos", group: "Técnica", icon: "Calculator", summary: "Presupuesto contractual, objetivo, costo real y análisis de precios.", features: ["Rubros e ítems", "APU", "Materiales", "Mano de obra", "Equipos", "Excel / PDF"] },
  { slug: "planning", label: "Planificación", group: "Técnica", icon: "GanttChartSquare", summary: "Cronogramas, hitos, Curva S y administración de plazos.", features: ["Cronograma", "Hitos", "Curva S", "Desvíos", "Prórrogas", "Neutralizaciones"] },
  { slug: "progress", label: "Avances", group: "Técnica", icon: "TrendingUp", summary: "Parte diario y avance físico-económico documentado.", features: ["Parte diario", "Fotografías", "Personal", "Equipos", "Clima", "Material recibido"] },
  { slug: "public-works", label: "Obra pública", group: "Técnica", icon: "Landmark", summary: "Ciclo contractual completo de licitación a recepción definitiva.", features: ["Licitación", "Contrato", "Anticipo", "Redeterminaciones", "Garantías", "Recepciones"] },
  { slug: "certificates", label: "Certificados", group: "Técnica", icon: "FileCheck2", summary: "Medición, deducciones, facturación, orden de pago y cobro.", features: ["Período", "Monto bruto", "Anticipo", "Fondo de reparo", "Neto", "Cobro"] },
  { slug: "dossiers", label: "Expedientes", group: "Técnica", icon: "Files", summary: "Seguimiento de expedientes, movimientos, saldos y alertas.", features: ["Organismo", "Número", "Movimientos", "Días sin movimiento", "Pago", "Documentos"] },
  { slug: "purchases", label: "Compras", group: "Abastecimiento", icon: "ShoppingCart", summary: "Solicitud, comparación, orden, recepción, factura y pago.", features: ["Solicitudes", "Cotizaciones", "Comparativa", "Orden de compra", "Remito", "Aprobación"] },
  { slug: "suppliers", label: "Proveedores", group: "Abastecimiento", icon: "ContactRound", summary: "Legajo fiscal, cuentas corrientes y desempeño comercial.", features: ["CUIT", "Condición IVA", "Contactos", "CBU", "Cuenta corriente", "Documentos"] },
  { slug: "logistics", label: "Logística", group: "Abastecimiento", icon: "Route", summary: "Pedidos, entregas y transferencias entre depósitos y obras.", features: ["Pedidos", "Entregas", "Transferencias", "Transporte", "Responsables", "Remitos"] },
  { slug: "stock", label: "Depósitos y stock", group: "Abastecimiento", icon: "Boxes", summary: "Existencias y movimientos valorizados por depósito y obra.", features: ["Materiales", "Stock mínimo", "Entradas", "Salidas", "Transferencias", "Valorización"] },
  { slug: "cash", label: "Cajas", group: "Finanzas", icon: "WalletCards", summary: "Caja central, administrativa y por obra con rendiciones.", features: ["Entregas", "Rendiciones", "Ingresos", "Egresos", "Saldo", "Comprobantes"] },
  { slug: "banks", label: "Bancos", group: "Finanzas", icon: "Landmark", summary: "Cuentas bancarias, cheques, conciliación y proyección.", features: ["Cuentas", "Movimientos", "Transferencias", "Cheques", "Conciliación", "Proyección"] },
  { slug: "payments", label: "Pagos y cobros", group: "Finanzas", icon: "ArrowLeftRight", summary: "Cuentas corrientes e imputación de pagos y cobros por obra.", features: ["Proveedores", "Clientes", "Retenciones", "Comprobantes", "Imputación", "Saldos"] },
  { slug: "accounting", label: "Contabilidad", group: "Finanzas", icon: "BookOpenCheck", summary: "Registración contable integrada por centro de costo.", features: ["Plan de cuentas", "Asientos", "Mayor", "Diario", "Balance", "Cierres"] },
  { slug: "taxes", label: "Impuestos", group: "Finanzas", icon: "ReceiptText", summary: "Posición fiscal y estimaciones de ARCA y DGR Corrientes.", features: ["IVA débito/crédito", "Retenciones", "Ganancias", "Seguridad Social", "IIBB", "VEP / DDJJ"] },
  { slug: "fleet", label: "Flota", group: "Operaciones", icon: "Truck", summary: "Vehículos, vencimientos, asignaciones y costos históricos.", features: ["Dominio", "Km", "Seguro", "RTO / VTV", "Chofer", "Costos"] },
  { slug: "drivers", label: "Choferes", group: "Operaciones", icon: "BadgeCheck", summary: "Legajos, licencias, vencimientos, viajes y viáticos.", features: ["Licencia", "Categoría", "Vencimientos", "Vehículo", "Viajes", "Viáticos"] },
  { slug: "fuel", label: "Combustible", group: "Operaciones", icon: "Fuel", summary: "Cargas por vehículo o máquina, rendimiento y alertas.", features: ["Litros", "Precio", "Km", "Horómetro", "Obra", "Rendimiento"] },
  { slug: "machinery", label: "Maquinarias", group: "Operaciones", icon: "Construction", summary: "Equipos, horómetros, operadores y costo por hora.", features: ["Equipo", "Horómetro", "Operador", "Combustible", "Reparaciones", "Costo / hora"] },
  { slug: "concrete", label: "Hormigonera", group: "Operaciones", icon: "Factory", summary: "Producción de hormigón, dosificación, remito y costo por m³.", features: ["Orden", "Dosificación", "m³", "Insumos", "Camión", "Costo / m³"] },
  { slug: "maintenance", label: "Mantenimiento", group: "Operaciones", icon: "Wrench", summary: "Mantenimiento preventivo y correctivo de flota, equipos e instalaciones.", features: ["Órdenes de trabajo", "Planes preventivos", "Mecánicos", "Repuestos consumidos", "Costos", "Alertas de service"] },
  { slug: "mechanics", label: "Mecánicos", group: "Operaciones", icon: "Wrench", summary: "Mecánicos internos/externos, especialidades, asignaciones y desempeño.", features: ["Legajo", "Especialidad", "Contacto", "OT asignadas", "Horas", "Historial"] },
  { slug: "spare-parts", label: "Repuestos", group: "Operaciones", icon: "Boxes", summary: "Catálogo y stock de repuestos con costo, mínimo y consumo por mantenimiento.", features: ["SKU", "Descripción", "Marca", "Stock", "Costo promedio", "Consumos"] },
  { slug: "fuel-estimates", label: "Estimación combustible", group: "Operaciones", icon: "Fuel", summary: "Estimación administrativa de litros por vehículo, obra y período contra consumo real.", features: ["Vehículo", "Período", "Km previstos", "Horas previstas", "Litros estimados", "Desvío real"] },
  { slug: "insurance", label: "Pólizas y cauciones", group: "Operaciones", icon: "ShieldCheck", summary: "Control integral de seguros, cauciones, vigencias, endosos, renovaciones y pagos.", features: ["Compañía emisora", "Comitente", "Vigencias", "Endosos", "Renovaciones", "Comprobantes"] },
  { slug: "unexpected-tasks", label: "Trabajos imprevistos", group: "Operaciones", icon: "ListChecks", summary: "Asignación y seguimiento de tareas imprevistas con prioridad, recursos, costo y cierre.", features: ["Alta inmediata", "Asignación", "Prioridad", "Vencimiento", "Costo", "Evidencias"] },
  { slug: "hr", label: "RR.HH.", group: "Personas", icon: "UsersRound", summary: "Personal, legajos, asistencia y distribución por obra.", features: ["Legajos", "Categoría", "Puesto", "Asistencia", "Horas", "Documentación"] },
  { slug: "personnel-control", label: "Control de personal", group: "Personas", icon: "ClipboardCheck", summary: "Asignación por obra, asistencia, horarios, horas extra, ubicación y novedades.", features: ["Asignaciones", "Presentismo", "Ingresos/Egresos", "Horas extra", "Novedades", "Centros de costo"] },
  { slug: "safety", label: "Seguridad e Higiene", group: "Personas", icon: "ShieldCheck", summary: "Gestión preventiva y documental de seguridad, EPP, capacitaciones, incidentes e inspecciones.", features: ["Aptos y credenciales", "EPP", "Capacitaciones", "Incidentes", "Inspecciones", "Vencimientos"] },
  { slug: "assets", label: "Inventario de activos", group: "Operaciones", icon: "Boxes", summary: "Inventario de bienes móviles y no móviles, herramientas, informática e instalaciones.", features: ["Móviles", "No móviles", "Herramientas", "Informática", "Asignaciones", "Vencimientos"] },
  { slug: "stakeholders", label: "Terceros y dependencias", group: "Abastecimiento", icon: "Building2", summary: "Maestro único de comitentes, contratistas, subcontratistas, proveedores, acreedores y aseguradoras.", features: ["Comitentes", "Contratistas", "Subcontratistas", "Proveedores", "Acreedores", "Aseguradoras"] },
  { slug: "payroll", label: "Sueldos", group: "Personas", icon: "Banknote", summary: "Liquidación y costo empresa distribuido por centro de costo.", features: ["Básico", "Adicionales", "Horas extra", "Cargas sociales", "Costo empresa", "Obra"] },
  { slug: "per-diems", label: "Viáticos", group: "Personas", icon: "MapPinned", summary: "Solicitud, autorización, comprobantes y rendición.", features: ["Empleado", "Destino", "Anticipo", "Gastos", "Comprobantes", "Saldo"] },
  { slug: "lodging", label: "Alojamientos", group: "Personas", icon: "BedDouble", summary: "Reservas y costos de alojamiento imputados por obra.", features: ["Hotel", "Personas", "Fechas", "Noches", "Factura", "Pago"] },
  { slug: "management", label: "Gerencia", group: "Dirección", icon: "ChartNoAxesCombined", summary: "Rentabilidad y flujo de fondos con drill-down al origen.", features: ["Rentabilidad", "Flujo de fondos", "Presupuesto vs real", "Deudas", "Impuestos", "Drill-down"] },
  { slug: "approvals", label: "Aprobaciones", group: "Dirección", icon: "ListChecks", summary: "Bandeja y motor configurable de aprobaciones.", features: ["Compras", "Pagos", "Viáticos", "Presupuestos", "Certificados", "Órdenes"] },
  { slug: "system", label: "Sistema", group: "Dirección", icon: "Settings", summary: "Usuarios, roles, parámetros, auditoría, backups y logs.", features: ["Usuarios", "Roles", "Permisos", "Numeradores", "Auditoría", "Backups"] },
];

export const groups = [
  "Principal",
  "Técnica",
  "Abastecimiento",
  "Finanzas",
  "Operaciones",
  "Personas",
  "Dirección",
];
